name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod download
      - name: Build
        run: |
          go generate ./...
          go build -v .
      - name: Test
        run: |
          go test -v ./...
          go test -v ./lib/...
      - name: Run
        run: |
          go run ./...
          go run ./cmd/app1/...
          go run ./cmd/app2/...
